backend:
  name: github # our repository provider
  repo: rezof/electrician
  branch: main # the main branch of our repo
  base_url: "https://electrician.vercel.app/" # our site's base URL
  auth_endpoint: "api/auth" # used together with base_url for our custom endpoints (more on this later)
media_folder: "public/images" # the folder we want to upload new images to
public_folder: "/images" # the folder our images should be fetched from
collections: # our content types, this is just an example!
  - name: "electrician"
    label: "Electrician"
    folder: "_sections/electrician"
    create: true
    slug: "electrician"
    fields:
      - label: Hero
        name: hero
        widget: object
        summary: "{{fields.title}}"
        fields:
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: desc, widget: text }
      - label: "Section 2"
        name: section_2
        summary: "{{fields.title}}"
        widget: list
        label_singular: "item"
        max: 3
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: desc, widget: text }
      - label: "Section 3"
        name: "section_3"
        summary: "{{fields.title}}"
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: desc, widget: text }
          - { label: Image, name: image, widget: image }
      - label: "Section 4"
        name: "section_4"
        widget: list
        label_singular: "feature"
        summary: "{{fields.title}}"
        fields:
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
      - label: "Section 5"
        name: "section_5"
        summary: "{{fields.title}}"
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Button Text, name: button_text, widget: string }
      - label: "Section 6"
        name: "section_6"
        widget: object
        summary: "{{fields.right_side.title}}"
        fields:
          - label: FAQ
            name: faq
            widget: list
            fields:
              - { name: question, label: Question, widget: text }
              - { name: answer, label: Answer, widget: text }
          - label: Right Side
            name: right_side
            widget: object
            fields:
              - { name: title, label: Title, widget: string }
              - { name: subtitle, label: Subtitle, widget: string }
              - name: bullets
                label: Bullets
                widget: list
                max: 4
                fields:
                  - name: Item
                    label: Bullet
                    widget: string
      - label: "Section 7"
        name: "section_7"
        summary: "{{fields.title}}"
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: text, widget: markdown }
      - label: "Reviews"
        name: "reviews"
        label_singular: "review"
        widget: list
        max: 3
        fields:
          - { label: Name, name: name, widget: string }
          - { label: image, name: image, widget: image }
          - { label: Review, name: review, widget: text }
          - { label: Platform, name: platform, widget: string }
      - label: "Section 9"
        name: "section_9"
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: markdown }
      - label: Section 10
        name: section_10
        widget: object
        fields:
          - name: banner
            label: Banner
            widget: obejct
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Text, name: text, widget: text }
          - name: our_services
            label: Our Services
            widget: obejct
            fields:
              - { label: Title, name: title, widget: string }
              - {
                  label: Services list,
                  name: services_list,
                  widget: list,
                  label_singular: "service",
                }
