backend:
  name: github # our repository provider
  repo: rezof/electrician
  branch: main # the main branch of our repo
  base_url: "https://electrician.vercel.app/" # our site's base URL
  auth_endpoint: "api/auth" # used together with base_url for our custom endpoints (more on this later)
media_folder: "public/images" # the folder we want to upload new images to
public_folder: "/images" # the folder our images should be fetched from
collections: # our content types, this is just an example!
  - name: "hero"
    label: "Hero Section"
    folder: "_sections/hero"
    create: true
    slug: "hero"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "text" }
  - name: "section_2"
    label: "Section 2"
    folder: "_sections/section_2"
    create: true
    slug: "section_2"
    fields:
      - label: Features
        name: features
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: desc, widget: text }
  - name: "section_3"
    label: "Section 3"
    folder: "_sections/section_3"
    create: true
    slug: "section_3"
    fields:
      - label: Features
        name: features
        widget: object
        fields:
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: desc, widget: text }
