backend:
  name: github # our repository provider
  repo: rezof/electrician
  branch: main # the main branch of our repo
  base_url: "https://electrician.vercel.app/" # our site's base URL
  auth_endpoint: "api/auth" # used together with base_url for our custom endpoints (more on this later)
media_folder: "public/images" # the folder we want to upload new images to
public_folder: "/images" # the folder our images should be fetched from
collections: # our content types, this is just an example!
  - name: "electrician"
    label: "Electrician"
    folder: "_sections/electrician"
    create: true
    slug: "electrician"
    fields:
      - label: Hero
        name: hero
        widget: object
        fields:
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: desc, widget: text }
      - label: "Section 2"
        name: section_2
        fields:
          - label: Features
            name: features
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: desc, widget: text }
      - label: "Section 3"
        name: "section_3"
        widget: object
        fields:
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: desc, widget: text }
      - label: "Section 4"
        name: "section_4"
        widget: list
        fields:
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
      - label: "Section 5"
        name: "section_5"
        widget: list
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Button Text, name: button_text, widget: string }
      - label: "Section 6"
        name: "section_6"
        widget: object
        fields:
          - label: FAQ,
            name: faq,
            widget: list,
            fields:
              - { name: question, label: Question, widget: text }
              - { name: answer, label: Answer, widget: text }
          - label: Right Side,
            name: right_side,
            widget: object,
            fields:
              - { name: title, label: Title, widget: string }
              - { name: subtitle, label: Subtitle, widget: string }
