import Head from "next/head";
import { HeroSection } from "@/sections/Hero";
import { Section2 } from "@/sections/Section2";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroSection />
        <Section2 />
      </main>
    </>
  );
}
